using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using FinalProject_JasonHuber.Models;

namespace FinalProject_JasonHuber.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<FinalProject_JasonHuberDBContext>
    {
        protected override void Seed(FinalProject_JasonHuberDBContext context)
        {


            var EventType = new List<EventType>
            {
                new EventType {EventTypeName = "Concert"},
                new EventType {EventTypeName = "Rave"},
                new EventType {EventTypeName = "Community Engagement"},
                new EventType {EventTypeName = "Political Event"},
                new EventType {EventTypeName = "School Event"},
                new EventType {EventTypeName = "Local Business Event"},
                new EventType {EventTypeName = "Sporting Event"},
                new EventType {EventTypeName = "Religious Event"},
                new EventType {EventTypeName = "Party"},
                new EventType {EventTypeName = "Theatre Event"},

            };


            var Event = new List<Event>
            {
               new Event {EventTitle = "JV Football", EventDescription = "Football", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"), OrganizerName = "Brunswick High School",  MaxTickets= 500, TicketsAvailable= 500, },
               new Event {EventTitle = "Varsity Football", EventDescription = "Football", EventCity = "North Royalton", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 400,},
               new Event {EventTitle = "JV Soccer", EventDescription = "Soccer", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 300,},
               new Event {EventTitle = "Varsity Soccer", EventDescription = "Soccer", EventCity = "Strongsville", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 500,},
               new Event {EventTitle = "Senior Prom", EventDescription = "Prom", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "School Event"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 400,},
               new Event {EventTitle = "HomeComing", EventDescription = "HomeComing", EventCity = "Solon", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "School Event"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 300,},
               new Event {EventTitle = "Class Elections", EventDescription = "Elections", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "School Event"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 500,},
               new Event {EventTitle = "Band Concert", EventDescription = "Band", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Concert"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 400,},
               new Event {EventTitle = "Choir Concert", EventDescription = "Choir", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Concert"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 300,},
               new Event {EventTitle = "Orchestra Concert", EventDescription = "Orchestra", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Concert"), OrganizerName = "Brunswick High School", MaxTickets= 500, TicketsAvailable= 200,},
               new Event {EventTitle = "D.A.R.E", EventDescription = "DARE", EventCity = "", EventState = "Strongsville", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Community Engagement"), OrganizerName = "Brunswick Police Department", MaxTickets= 500, TicketsAvailable= 500,},
               new Event {EventTitle = "Meet the Police", EventDescription = "Police event", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Community Engagement"), OrganizerName = "Brunswick Police Department", MaxTickets= 500, TicketsAvailable= 400,},
               new Event {EventTitle = "Home Safety Awareness", EventDescription = "Safety", EventCity = "Medina", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Community Engagement"), OrganizerName =  "Brunswick Police Department", MaxTickets= 500, TicketsAvailable= 300,},
               new Event {EventTitle = "Child Saftey", EventDescription = "Safety", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Community Engagement"), OrganizerName = "Brunswick Police Department", MaxTickets= 500, TicketsAvailable= 200,},
               new Event {EventTitle = "Gun Buy Back", EventDescription = "BuyBack", EventCity = "Canton", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Community Engagement"), OrganizerName = "Brunswick Police Department", MaxTickets= 500, TicketsAvailable= 100,},
               new Event {EventTitle = "Meeting on Road Condition", EventDescription = "Meeting on Road Condition", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Political Event"), OrganizerName = "Brunswick City Council", MaxTickets= 500, TicketsAvailable= 500,},
               new Event {EventTitle = "Meeting on Community Issues", EventDescription = "Meeting on Community Issues", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Political Event"), OrganizerName ="Brunswick City Council", MaxTickets= 500,TicketsAvailable= 700,},
               new Event {EventTitle = "Proposals", EventDescription = "Proposals", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Political Event"), OrganizerName = "Brunswick City Council", MaxTickets= 500, TicketsAvailable= 500,},
               new Event {EventTitle = "Open House", EventDescription = "Open House", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Political Event"), OrganizerName ="Brunswick City Council", MaxTickets= 500, TicketsAvailable= 600,},
               new Event {EventTitle = "Adult Soccer", EventDescription = "Soccer", EventCity = "Brunswick", EventState = "Ohio",EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"),OrganizerName = "Brunswick Recreation Center", MaxTickets= 500, TicketsAvailable= 400,},
               new Event {EventTitle = "Adult Basketball", EventDescription = "Basketball", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"),OrganizerName = "Brunswick Recreation Center", MaxTickets= 500, TicketsAvailable= 200,},
               new Event {EventTitle = "Karate", EventDescription = "Karate", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 500,},
               new Event {EventTitle = "Judo", EventDescription = "Judo", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Sporting Event"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 300,},
               new Event {EventTitle = "Romeo and Juliet", EventDescription = "Play", EventCity = "Strongsville", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Theatre Event"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 700,},
               new Event {EventTitle = "The Phantom of the Opera", EventDescription = "Play", EventCity = "Strongsville", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Theatre Event"),  OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 800,},
               new Event {EventTitle = "Jodie's 80th Birthday", EventDescription = "Party for Jodie", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Party"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 400,},
               new Event {EventTitle = "BassTime", EventDescription = "Rave show", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Rave"),  OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 500,},
               new Event {EventTitle = "AC/DC CoverBand", EventDescription = "New Cover Band", EventCity = "Brunswick", EventState = "Ohio", EventStartDate = new DateTime(2019,2,12) ,EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Concert"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 800,},
               new Event {EventTitle = "Aerosmith CoverBand", EventDescription = "New cover band", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Concert"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 400,},
               new Event {EventTitle = "Meatloaf CoverBand", EventDescription = "New cover band", EventCity = "Brunswick", EventState = "Ohio", EventStartDate =  new DateTime(2019,2,12),EventEndDate = new DateTime(2019,2,12), EventStartTime = "10:00 A.M.", EventEndTime = "10:00 A.M.", EventType= EventType.Single(e => e.EventTypeName == "Concert"), OrganizerName = "Brunswick Recreation Center", MaxTickets= 500,TicketsAvailable= 200,},
            };
            base.Seed(context);
        }
    }
}